import { Suspense } from 'react';
import type { Metadata } from 'next';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import CTABand from '@/components/CTABand';
import CatalogueClient from './CatalogueClient';
import { getCategories, getProducts, getUseCaseFilters } from '@/lib/queries';

const BASE_DESC = 'Shop water pumps, RO & filtration systems, fountains, pressure washers, air compressors and hydraulic equipment in Chennai. 70+ products from Kent, CRI, Grundfos, Kirloskar and more. Workshop repair at Parrys.';

export const revalidate = 60;

// `/catalogue?cat=X` and `?cat=X&sub=Y` are permanently redirected to the
// path-based routes in next.config.ts, so those params never reach this page —
// per-category metadata is generated by /catalogue/[category] instead.
export const metadata: Metadata = {
  title: { absolute: 'Water Pumps, RO Systems & Industrial Equipment in Chennai' },
  description: BASE_DESC,
  alternates: { canonical: '/catalogue' },
  openGraph: {
    title: 'Water Pumps, RO Systems & Industrial Equipment in Chennai',
    description: BASE_DESC,
    url: '/catalogue',
    type: 'website',
  },
};

export default async function CataloguePage() {
  const [categories, products, ucFilters] = await Promise.all([
    getCategories().catch(() => []),
    getProducts().catch(() => []),
    getUseCaseFilters(),
  ]);

  // Attach use-case slugs so the client can filter by them.
  for (const p of products) {
    p.ucSlugs = ucFilters.byProduct.get(p._id) ?? [];
  }

  return (
    <>
      <Header active="products" />
      <main>
      <Suspense fallback={<div style={{ padding: '80px 0', textAlign: 'center', color: 'var(--muted)' }}>Loading products…</div>}>
        <CatalogueClient categories={categories} products={products} useCases={ucFilters.options} />
      </Suspense>
      <CTABand />
      </main>
      <Footer />
    </>
  );
}
